version: '2'
services:
  cli:
    container_name: "phryer-cli"
    volumes:
      - ./phryer:/phish-phryer/phryer
    build: .
    ports:
      - "9050:9050"
    tty: true
    stdin_open: true
  webserver:
    container_name: "phryer-web"
    image: nginx:mainline-bullseye
    ports:
      - "8080:80"
    volumes:
      - ./webserver:/usr/share/nginx/html/
    tty: false
    stdin_open: false