version: '1'
services:
  cli:
    volumes:
      - ./phish-phryer:/phish-phryer/phryer
    build: .
    ports:
      - "9050:9050"
    tty: true
    stdin_open: true
  webserver:
    image: nginx:mainline-bullseye
    ports:
      - "8080:80"
    volumes:
      - ./webserver:/usr/share/nginx/html/
    tty: false
    stdin_open: false