[tool.poetry]
name = "phish-phryer"
version = "0.0.1"
description = ""
authors = ["hullabrian"]

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.4.3"
requests = "^2.28.1"
typer = "^0.6.1"
Flask = "^2.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
